image: node:18-alpine

stages:
   - start
   - test
   - build

start_app:
   stage: start
   before_script:
      - npm install -f
   script:
      - npm run dev -f &

app test:
   stage: test
   before_script:
      - npm install -f
   script:
      - npm run dev -f &
      - sleep 10
      - apk --no-cache add curl
      - curl "http://localhost:3000"

build_image:
   stage: build
   image: docker:24.0.4-cli-alpine3.18
   services:
      - docker:24.0.4-dind
#   variables:
#      - DOCKER_TLS_CERTDIR: "/certs"
   before_script:
      - docker login -u bespoque -p fyu_MBT8mfp8dpc1uea
   script:
      - docker build -t bespoque/rhm:1.0 .
      - docker push bespoque/rhm:1.0


