stages:         
  - build main
  - build dev

variables:
   STAGING_DOMAIN: dev.rhmapp.irs.kg.gov.ng
   PRODUCTION_DOMAIN: rhmapp.irs.kg.gov.ng
   TEST_DB: rhmapi
   LIVE_DB: rhmlive

build-job staging:       
  stage: build dev
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - sudo kill -9 $(sudo lsof -t -i:3000)
    - sed -i "s/%%DB%%/$TEST_DB/" ./src/config/url.js
    - sudo rm -rf /var/www/rhm/*
    - sudo cp -r * /var/www/rhm/
    - sudo cp -r . /var/www/rhm/
    - sudo rm -rf *
    - cd /var/www/rhm
    - npm i
    - npm run build
    - npx next start
  tags :  
     - rhm
  only :
     - main 
 
build-job main:       
  stage: build main
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - sed -i "s/%%DB%%/$LIVE_DB/" ./src/config/url.js
    - sudo rm -rf /var/www/rhm/*
    - sudo cp -r * /var/www/rhm/
    - sudo cp -r . /var/www/rhm/
    - sudo rm -rf *
    - cd /var/www/rhm
    - npm i
    - npm run build
    - npx next start
  tags :  
     - rhm-dev
  only :
     - dev 