image: node:18-alpine

stages:
   - test
   - build
   - deploy

start_app:
   stage: test
   before_script:
      - npm install -f
   script:
      - npm run dev -f &
 #     - sleep 10
 #     - apk --no-cache add curl
 #     - curl "http://localhost:3000"

build_image:
   stage: build
   image: docker:24.0.4-cli-alpine3.18
   services:
      - docker:24.0.4-dind
#   variables:
#      - DOCKER_TLS_CERTDIR: "/certs"
   before_script:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
   script:
      - docker build -t bespoque/rhm:prod-1.2 .
      - docker push bespoque/rhm:prod-1.2

deploy_prod:
   stage: deploy
   script:
      - echo "Deploy to production server"
   environment:
      name: production
      url: http://rhm.hrsystems.com.ng
   image:
      name: bitnami/kubectl:latest
      entrypoint: ['']
   script:
      - kubectl config get-contexts
      - kubectl config use-context bespoqueng/rhmlive:rhm-agent
      - kubectl get pods
      - kubectl apply -f ./manifest/.

