stages:         
  - build main
 
build-job main:       
  stage: build main
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - sudo rm -rf /var/www/rhm/*
    - sudo cp -r * /var/www/rhm/
    - sudo cp -r . /var/www/rhm/
    - sudo rm -rf *
  tags :  
     - rhm
  only :
     - main 